package garmtool

import (
	"context"
	"errors"
	"strings"
	"testing"

	"github.com/garm-ai/garm/contracts/wire"
	"github.com/nats-io/nats.go"
	"github.com/nats-io/nats.go/micro"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/known/wrapperspb"

	"github.com/garm-ai/tool-go/toolbind"
)

// The runtime is only useful to generated code if it is a Registrar, and the
// generator never imports it — so nothing but this line would notice the
// signature drifting apart from the seam.
var _ toolbind.Registrar = (*Service)(nil)

const addRoute = "/calc.v1.Calculator/Add"

func addRef() toolbind.ToolRef {
	return toolbind.ToolRef{
		FQN:             "calc.v1.Calculator.Add",
		Subject:         wire.Subject(addRoute),
		Method:          "Add",
		Service:         wire.QueueGroup(addRoute),
		ContractVersion: "v1.4.0",
		DescriptorHash:  "sha256:abc",
	}
}

func newString() proto.Message { return &wrapperspb.StringValue{} }

func echo(_ context.Context, req proto.Message) (proto.Message, error) {
	return wrapperspb.String(req.(*wrapperspb.StringValue).GetValue()), nil
}

// recorder stands in for a micro.Request so the handler's decisions can be
// read back without a server. Only what the handler touches is implemented;
// the rest panics rather than returning a zero value, because a silently
// empty Headers() would make a future test pass for the wrong reason.
type recorder struct {
	data []byte

	code, description string
	body              []byte
	errored, answered bool
}

func (r *recorder) Respond(b []byte, _ ...micro.RespondOpt) error {
	r.answered, r.body = true, b
	return nil
}

func (r *recorder) Error(code, description string, _ []byte, _ ...micro.RespondOpt) error {
	r.errored, r.code, r.description = true, code, description
	return nil
}

func (r *recorder) Data() []byte                               { return r.data }
func (r *recorder) RespondJSON(any, ...micro.RespondOpt) error { panic("the handler marshals itself") }
func (r *recorder) Headers() micro.Headers                     { panic("the handler reads no headers") }
func (r *recorder) Subject() string                            { panic("the handler routes by registration") }
func (r *recorder) Reply() string                              { panic("micro owns the reply subject") }

// call drives the handler the way Run does, with one endpoint and one request.
func call(t *testing.T, h toolbind.Handler, data []byte) *recorder {
	t.Helper()
	s := New("calc", "v0.1.0")
	if err := s.Endpoint(addRef(), newString, h); err != nil {
		t.Fatalf("registering: %v", err)
	}
	r := &recorder{data: data}
	s.handle(context.Background(), s.eps[addRef().Subject], r)
	return r
}

func marshal(t *testing.T, m proto.Message) []byte {
	t.Helper()
	b, err := proto.Marshal(m)
	if err != nil {
		t.Fatalf("marshalling the test request: %v", err)
	}
	return b
}

// Two handlers claiming one subject means the second silently wins, and which
// one that is depends on registration order a generator chose. The failure has
// to arrive at startup, where a person is watching.
func TestTwoHandlersOnOneSubjectAreRefused(t *testing.T) {
	s := New("calc", "v0.1.0")
	if err := s.Endpoint(addRef(), newString, echo); err != nil {
		t.Fatalf("the first registration: %v", err)
	}

	// A different FQN on the same subject, because it is the subject that
	// decides where a request lands — matching on FQN would let a rename slip
	// a second subscriber onto a live route.
	second := addRef()
	second.FQN = "calc.v1.Calculator.Plus"
	err := s.Endpoint(second, newString, echo)
	if err == nil {
		t.Fatal("registering a second handler on one subject was allowed")
	}
	if !strings.Contains(err.Error(), second.Subject) {
		t.Errorf("the error does not name the subject at fault: %v", err)
	}
}

// One process advertises ONE descriptor hash and a daemon reconciles against
// it. Serving two contracts would make that advertisement a half-truth, and
// the half it left out is the half that drifted.
func TestBindingsFromTwoContractsAreRefused(t *testing.T) {
	s := New("calc", "v0.1.0")
	if err := s.Endpoint(addRef(), newString, echo); err != nil {
		t.Fatalf("the first registration: %v", err)
	}

	other := addRef()
	other.FQN = "calc.v1.Calculator.Sub"
	other.Subject = wire.Subject("/calc.v1.Calculator/Sub")
	other.DescriptorHash = "sha256:def"
	err := s.Endpoint(other, newString, echo)
	if err == nil {
		t.Fatal("a binding generated from a different contract was accepted")
	}
	for _, want := range []string{other.FQN, "sha256:def", "sha256:abc"} {
		if !strings.Contains(err.Error(), want) {
			t.Errorf("the error does not mention %q, so it does not say which contract to rebuild: %v", want, err)
		}
	}
}

// An unhashed binding is one generated by an older generator, not one from a
// second contract. Refusing it would make upgrading the generator a flag day
// for every service; what must not happen is it overwriting the hash the
// service already advertises.
func TestABindingWithNoHashJoinsWithoutChangingWhatIsAdvertised(t *testing.T) {
	s := New("calc", "v0.1.0")
	if err := s.Endpoint(addRef(), newString, echo); err != nil {
		t.Fatalf("the first registration: %v", err)
	}

	unhashed := addRef()
	unhashed.FQN = "calc.v1.Calculator.Sub"
	unhashed.Subject = wire.Subject("/calc.v1.Calculator/Sub")
	unhashed.DescriptorHash = ""
	if err := s.Endpoint(unhashed, newString, echo); err != nil {
		t.Fatalf("an unhashed binding was refused: %v", err)
	}
	if s.hash != "sha256:abc" {
		t.Errorf("the advertised hash became %q; an unhashed binding erased the one that was known", s.hash)
	}
}

// Generated code passes these, so a nil here means the generator emitted
// something wrong — which is worth catching at registration rather than as a
// nil dereference on the first request of the day.
func TestAnEndpointNeedsASubjectAConstructorAndAHandler(t *testing.T) {
	for _, c := range []struct {
		name       string
		subject    string
		newRequest func() proto.Message
		handler    toolbind.Handler
	}{
		{"no subject", "", newString, echo},
		{"no constructor", wire.Subject(addRoute), nil, echo},
		{"no handler", wire.Subject(addRoute), newString, nil},
	} {
		t.Run(c.name, func(t *testing.T) {
			ref := addRef()
			ref.Subject = c.subject
			s := New("calc", "v0.1.0")
			if err := s.Endpoint(ref, c.newRequest, c.handler); err == nil {
				t.Fatalf("%s was accepted", c.name)
			}
		})
	}
}

// NATS micro rejects a leading "v" as invalid SemVer, and every Go module
// version carries one — so the obvious thing to pass, the version of the
// module being served, would fail at startup with a message that never
// mentions the v.
func TestALeadingVIsStrippedFromTheVersion(t *testing.T) {
	if got := New("calc", "v1.2.3").version; got != "1.2.3" {
		t.Errorf("version = %q, which micro refuses to start on", got)
	}
	if got := New("calc", "1.2.3").version; got != "1.2.3" {
		t.Errorf("version = %q; a version that was already bare was altered", got)
	}
}

// A process that serves nothing was configured wrong: a binding was not linked
// in, or its Register was never called. Running happily is how that survives
// to production and shows up as a caller timing out.
func TestRunWithNothingRegisteredIsAnError(t *testing.T) {
	// A nil connection is safe here only because the emptiness check comes
	// first; if that stops being true this test panics rather than passing.
	if err := New("calc", "v0.1.0").Run(context.Background(), (*nats.Conn)(nil)); err == nil {
		t.Fatal("a service with nothing to serve started")
	}
}

// The daemon marshalled the request from a descriptor in its catalogue, so a
// parse failure is the two sides holding different schemas — not this
// handler misbehaving. Reporting it as a handler error sends whoever is
// paged to read the wrong code.
func TestARequestThatDoesNotParseSaysTheContractsDisagree(t *testing.T) {
	r := call(t, echo, []byte{0xff, 0xff, 0xff, 0xff})
	if !r.errored {
		t.Fatal("unparseable bytes were answered as a success")
	}
	if r.code != "400" {
		t.Errorf("code = %q; a contract mismatch is the caller's message, not a service fault", r.code)
	}
	if !strings.Contains(r.description, "contract") {
		t.Errorf("description = %q, which does not point at the contract", r.description)
	}
}

// (nil, nil) would otherwise reply with an empty body that unmarshals into a
// zero-valued response — a success no caller can tell apart from a genuine
// empty result.
func TestAHandlerThatReturnsNothingAtAllIsAnError(t *testing.T) {
	nothing := func(context.Context, proto.Message) (proto.Message, error) { return nil, nil }
	r := call(t, nothing, marshal(t, wrapperspb.String("2")))
	if r.answered {
		t.Fatal("a handler that returned nothing produced a successful reply")
	}
	if r.code != "500" {
		t.Errorf("code = %q, want 500", r.code)
	}
}

// The nil that actually arrives is not the nil the obvious check catches.
//
// Generated code adapts a typed handler by returning its result straight into
// a proto.Message, so a handler that returned (*pb.Reply)(nil) reaches the
// runtime as a NON-nil interface holding a nil pointer — and proto.Marshal
// encodes that to zero bytes with no error. A guard written as `resp == nil`
// passes every direct test and misses every real one, replying success with
// an empty body to a handler that answered nothing.
func TestAHandlerThatReturnsATypedNilIsAnErrorToo(t *testing.T) {
	typedNil := func(context.Context, proto.Message) (proto.Message, error) {
		var resp *wrapperspb.StringValue
		return resp, nil
	}
	r := call(t, typedNil, marshal(t, wrapperspb.String("2")))
	if r.answered {
		t.Fatalf("a nil response was replied to as a success with body %v", r.body)
	}
	if r.code != "500" {
		t.Errorf("code = %q, want 500", r.code)
	}
}

// The handler's own words reach the caller, because a tool failing for a
// reason it can state is the common case and "500" alone is not actionable.
func TestAHandlerErrorReachesTheCallerVerbatim(t *testing.T) {
	failing := func(context.Context, proto.Message) (proto.Message, error) {
		return nil, errors.New("divide by zero")
	}
	r := call(t, failing, marshal(t, wrapperspb.String("2")))
	if r.description != "divide by zero" {
		t.Errorf("description = %q; the handler's reason did not survive", r.description)
	}
	if r.code != "500" {
		t.Errorf("code = %q, want 500", r.code)
	}
}

// A response the handler built but protobuf cannot encode must not become a
// truncated or empty success — the caller would treat it as the answer.
func TestAResponseThatCannotBeEncodedIsAnErrorNotAnEmptyReply(t *testing.T) {
	invalid := func(context.Context, proto.Message) (proto.Message, error) {
		return wrapperspb.String(string([]byte{0xff, 0xfe})), nil
	}
	r := call(t, invalid, marshal(t, wrapperspb.String("2")))
	if r.answered {
		t.Fatal("an unencodable response was replied to as a success")
	}
	if r.code != "500" {
		t.Errorf("code = %q, want 500", r.code)
	}
}

// The handler is handed the parsed request, not the bytes, and its response
// goes back encoded. This is the whole hop; everything else in the file is a
// way for it to go wrong.
func TestTheHandlerSeesTheParsedRequestAndItsResponseIsEncoded(t *testing.T) {
	r := call(t, echo, marshal(t, wrapperspb.String("hello")))
	if !r.answered {
		t.Fatalf("no reply; error was %q %q", r.code, r.description)
	}
	var got wrapperspb.StringValue
	if err := proto.Unmarshal(r.body, &got); err != nil {
		t.Fatalf("the reply is not the response message: %v", err)
	}
	if got.GetValue() != "hello" {
		t.Errorf("value = %q, want %q", got.GetValue(), "hello")
	}
}

// Subject and QueueGroup used to be implemented here AND in the daemon, in
// different repositories, with nothing keeping them identical. Re-exporting
// is the fix; this pins that they are still the contract's own functions and
// not local copies that drifted back in.
func TestTheNamingIsTheContractsAndNotACopy(t *testing.T) {
	if Subject(addRoute) != wire.Subject(addRoute) {
		t.Errorf("Subject diverged from the contract: %q vs %q", Subject(addRoute), wire.Subject(addRoute))
	}
	if QueueGroup(addRoute) != wire.QueueGroup(addRoute) {
		t.Errorf("QueueGroup diverged from the contract: %q vs %q", QueueGroup(addRoute), wire.QueueGroup(addRoute))
	}
}
